scenario_cfg:
  dataset_name: ScienceQA_LAMM
  base_data_path: /mnt/petrelfs/chenzeren/archive/LAMM-src/data/2D_Benchmark

eval_cfg:
  instruction_cfg:
    query_type: standard_query
  inferencer_cfg:
    inferencer_type: Direct
    batch_size: 8
    CoT: True
    max_new_tokens: 256
  metric_cfg:
    metric_type: LAMM