scenario_cfg:
  dataset_name: STL10_LAMM
  base_data_path: ./data/LAMM/2D_Benchmark

eval_cfg:
  instruction_cfg:
    query_type: standard_query
  inferencer_cfg:
    inferencer_type: Direct
    batch_size: 1 #32
  metric_cfg:
    metric_type: LAMM