scenario_cfg:
  dataset_name: OctaviusPCLDataset
  base_data_path: ../data/3D_Benchmark
  task_name: Classification
  inference_dataset_name: scannet
  vision_root_path: /mnt/petrelfs/chenzeren/LAMM-Det3d/data/3D_Instruct

eval_cfg:
  instruction_cfg:
    query_type: standard_query
  inferencer_cfg:
    inferencer_type: Direct3D
    batch_size: 1
  metric_cfg:
    metric_type: Octavius3D
