scenario_cfg:
  dataset_name: OctaviusPCLDataset
  base_data_path: ../data/LAMM/3D_Benchmark
  task_name: Caption
  inference_dataset_name: scannet
  vision_root_path: ../data/LAMM/Octavius_3D_Instruct

eval_cfg:
  instruction_cfg:
    query_type: standard_query
  inferencer_cfg:
    inferencer_type: Direct3D
    batch_size: 1
  metric_cfg:
    metric_type: Octavius3D